routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'OverviewController@index');
Route::get('/about', 'OverviewController@about');
Route::get('/photos', 'OverviewController@photos');
Route::get('/testimonials', 'OverviewController@testimonials');
Route::get('/contact', 'OverviewController@contact');
Route::get('/disclaimer', 'OverviewController@disclaimer');

Route::group([
    'middleware' => 'auth',
    'as' => 'admin.',
    'prefix' => 'admin',
], function() {

    Route::get('/', ['as' => 'index', 'uses' => 'AdminController@index']);
    Route::resource('photos', 'PhotoController');
    Route::resource('testimonials', 'TestimonialController');
    Route::resource('swaps', 'SwapController');

    Route::group([
        'as' => 'game.',
        'prefix' => 'game',
    ], function() {
        Route::get('/{locale?}', ['as' => 'start', 'uses' => 'SessionController@start']);

        Route::get('/top-eight', 'ValueController@getTopEight');

        Route::post('players', 'PlayerController@store');

        Route::post('sessions/{session_id}', 'SessionController@saveAll');

        Route::get('sessions/restart', 'SessionController@restart');
    });

});

Auth::routes(['register' => false]);

app/Testimonial.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Testimonial extends Model
{
    protected $fillable = [
        'name',
        'url'
    ];
}

app/Http/Controllers/TestimonialController.php
<?php

namespace App\Http\Controllers;

use App\Testimonial;
use Illuminate\Http\Request;

class TestimonialController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.testimonials.index')
            ->with('testimonials', Testimonial::all())
        ;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.testimonials.form')
            ->with('testimonial', new Testimonial())
        ;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $url = $request->file('file')->store('testimonials', 'public');
        Testimonial::create([
            'name' => $request->name,
            'url' => $url,
        ]);
        return redirect()->route('admin.testimonials.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Testimonial  $testimonial
     * @return \Illuminate\Http\Response
     */
    public function show(Testimonial $testimonial)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Testimonial  $testimonial
     * @return \Illuminate\Http\Response
     */
    public function edit(Testimonial $testimonial)
    {
        return view('admin.testimonials.form')
            ->with('testimonial', $testimonial)
        ;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Testimonial  $testimonial
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Testimonial $testimonial)
    {
        $file = $request->file('file');
        if(isset($file)) {
            $url = $file->store('testimonials', 'public');
        }
        $testimonial->update([
            'name' => $request->name ?? $testimonial->name,
            'url' => $url ?? $testimonial->url,
        ]);
        return redirect()->route('admin.testimonials.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Testimonial  $testimonial
     * @return \Illuminate\Http\Response
     */
    public function destroy(Testimonial $testimonial)
    {
        Storage::disk('public')->delete($testimonial->url);
        $testimonial->delete();
        return response()->json(["success" => true]);
    }
}

resources/views/admin/testimonials/form.blade.php
@extends('layouts.app')
@section('content')
	@include('includes.header')

	<div class="container">
		@if($testimonial->id == null)
			{{ Form::open(['route' => 'admin.testimonials.store', 'method' => 'post', 'files' => true]) }}
		@else
			{{ Form::open(['route' => ['admin.testimonials.update', $testimonial->id], 'method' => 'put', 'files' => true]) }}
		@endif
    		<h2>Testimonial</h2>
    		<div class="form-group">
    			<label for="name">Naam</label>
    			<input class="form-control" type="text" name="name" id="name" value="{{ $testimonial->name }}" placeholder="Titel van de testimonial">
			</div>
    		@if(isset($testimonial))
    			<video width="320" height="240" controls>
                    <source src="{{ asset( Storage::url( $testimonial->url ) ) }}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
    		@endif
    		<div class="custom-file">
    			<input type="file" class="custom-file-input" name="file" id="file">
    			<label class="custom-file-label" for="file">Kies bestand...</label>
			</div>
			<div class="mt-3">
				<button type="submit" class="btn btn-primary">Opslaan</button> <a href="{{ route('admin.testimonials.index') }}" class="btn">Annuleren</a>
			</div>
		{{ Form::close() }}
	</div>

	@include('includes.footer')
@stop

resources/views/admin/testimonials/index.blade.php
@extends('layouts.app')
@section('content')
	@include('includes.header');

	<div class="container">
	    <div class="row">
            <div class="col">
                <h2>Testimonials</h2>
            </div>
            <div class="col">
                <a href="{{ route('admin.testimonials.create') }}">Toevoegen</a>
            </div>
        </div>
    	<div>
    		@foreach($testimonials as $testimonial)
    		    <div class="photo-wrapper col-3" id="testimonial{{ $testimonial->id }}">
    		        <div class="d-block">
                        <a href="{{ route('admin.testimonials.edit', $testimonial) }}">{{ $testimonial->name }}</a>
                        <a class="float-right text-danger" href="#" onclick="deleteTestimonial({{ $testimonial->id }}, '{{ $testimonial->name }}')">X</a>
                    </div>
                    <video width="320" height="240" controls>
                        <source src="{{ asset( Storage::url( $testimonial->url ) ) }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </div>
    		@endforeach
    	</div>
	</div>

	@include('includes.footer')
@stop

@section('js')
	<script>
		function deleteTestimonial(id, name) {
			if(confirm("Wilt u de testimonial " + name + " verwijderen?")) {
    			let url = "{{ route('admin.testimonials.destroy', ':id') }}";
    			console.log(url);
    			url = url.replace(":id", id);
        		axios.delete(url).then(response => {
    				$("#testimonial" + id).hide();
    			});
			};
		}
	</script>
@stop