routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'OverviewController@index');
Route::get('/about', 'OverviewController@about');
Route::get('/photos', 'OverviewController@photos');
Route::get('/testimonials', 'OverviewController@testimonials');
Route::get('/contact', 'OverviewController@contact');
Route::get('/disclaimer', 'OverviewController@disclaimer');

Route::group([
    'middleware' => 'auth',
    'as' => 'admin.',
    'prefix' => 'admin',
], function() {

    Route::get('/', ['as' => 'index', 'uses' => 'AdminController@index']);
    Route::resource('photos', 'PhotoController');
    Route::resource('testimonials', 'TestimonialController');
    Route::resource('swaps', 'SwapController');

    Route::group([
        'as' => 'game.',
        'prefix' => 'game',
    ], function() {
        Route::get('/{locale?}', ['as' => 'start', 'uses' => 'SessionController@start']);

        Route::get('/top-eight', 'ValueController@getTopEight');

        Route::post('players', 'PlayerController@store');

        Route::post('sessions/{session_id}', 'SessionController@saveAll');

        Route::get('sessions/restart', 'SessionController@restart');
    });

});

Auth::routes(['register' => false]);

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = [
        'name',
        'url'
    ];
}

app/Http/Controllers/PhotoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Photo;

class PhotoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        return view('admin.photos.index')
            ->with('photos', Photo::all())
        ;
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.photos.form')
            ->with('photo', new Photo())
        ;
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $url = $request->file('file')->store('photos', 'public');
        Photo::create([
            'name' => $request->name,
            'url' => $url,
        ]);
        return redirect()->route('admin.photos.index');
    }
    
    /**
     * Display the specified resource.
     *
     * @param  \App\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function show(Photo $photo)
    {
        //
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function edit(Photo $photo)
    {
        return view('admin.photos.form')
            ->with('photo', $photo)
        ;
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Photo $photo)
    {
        $file = $request->file('file');
        if(isset($file)) {
            $url = $file->store('photos', 'public');
        }
        $photo->update([
            'name' => $request->name ?? $photo->name,
            'url' => $url ?? $photo->url,
        ]);
        return redirect()->route('admin.photos.index');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Photo $photo)
    {
        Storage::disk('public')->delete($photo->url);
        $photo->delete();
        return response()->json(["success" => true]);
    }
}

resources/views/admin/photos/form.blade.php
@extends('layouts.app')
@section('content')
	@include('includes.header')
	
	<div class="container">
		@if($photo->id == null)
			{{ Form::open(['route' => 'admin.photos.store', 'method' => 'post', 'files' => true]) }}	
		@else
			{{ Form::open(['route' => ['admin.photos.update', $photo->id], 'method' => 'put', 'files' => true]) }}
		@endif
    		<h2>Foto</h2>
    		<div class="form-group">
    			<label for="name">Naam</label>
    			<input class="form-control" type="text" name="name" id="name" value="{{ $photo->name }}" placeholder="Titel van de foto">
			</div>
    		@if(isset($photo))
    			<div class="photo-wrapper col-3">
    				<img src="{{ asset(Storage::url($photo->url)) }}" class="img-fluid" alt="{{ $photo->name }}">
				</div>
    		@endif
    		<div class="custom-file">
    			<input type="file" class="custom-file-input" name="file" id="file">
    			<label class="custom-file-label" for="file">Kies bestand...</label>
			</div>
			<div class="mt-3">
				<button type="submit" class="btn btn-primary">Opslaan</button> <a href="{{ route('admin.photos.index') }}" class="btn">Annuleren</a>
			</div>
		{{ Form::close() }}
	</div>
	
	@include('includes.footer')
@stop

resources/views/admin/photos/index.blade.php
@extends('layouts.app')
@section('content')
	@include('includes.header');
	
	<div class="container">
		<div class="row">
        	<div class="col">
        		<h2>Foto's</h2>
    		</div>
    		<div class="col">
    			<a href="{{ route('admin.photos.create') }}">Toevoegen</a>
    		</div>
		</div>
    	<div>
    		@foreach($photos as $photo)
    			<div class="photo-wrapper col-3" id="photo{{ $photo->id }}">
    				<div class="d-block">
    					<a href="{{ route('admin.photos.edit', $photo) }}">{{ $photo->name }}</a> 
    					<a class="float-right text-danger" href="#" onclick="deletePhoto({{ $photo->id }}, '{{ $photo->name }}')">X</a>
					</div>
    				<img class="img-fluid img-thumbnail" src="{{ asset( Storage::url($photo->url) ) }}" alt="{{ $photo->name }}" title="{{ $photo->name }}">
				</div>
    		@endforeach
    	</div>
	</div>
	
	@include('includes.footer')
@stop

@section('js')
	<script>
		function deletePhoto(id, name) {
			if(confirm("Wilt u de foto " + name + " verwijderen?")) {
    			let url = "{{ route('admin.photos.destroy', ':id') }}";
    			console.log(url);
    			url = url.replace(":id", id);
        		axios.delete(url).then(response => {
    				document.querySelector("#photo" + id).style.display = "none";    
    			});
			};
		}
	</script>
@stop