routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'OverviewController@index');
Route::get('/about', 'OverviewController@about');
Route::get('/photos', 'OverviewController@photos');
Route::get('/testimonials', 'OverviewController@testimonials');
Route::get('/contact', 'OverviewController@contact');
Route::get('/disclaimer', 'OverviewController@disclaimer');

Route::group([
    'middleware' => 'auth',
    'as' => 'admin.',
    'prefix' => 'admin',
], function() {

    Route::get('/', ['as' => 'index', 'uses' => 'AdminController@index']);
    Route::resource('photos', 'PhotoController');
    Route::resource('testimonials', 'TestimonialController');
    Route::resource('swaps', 'SwapController');

    Route::group([
        'as' => 'game.',
        'prefix' => 'game',
    ], function() {
        Route::get('/{locale?}', ['as' => 'start', 'uses' => 'SessionController@start']);

        Route::get('/top-eight', 'ValueController@getTopEight');

        Route::post('players', 'PlayerController@store');

        Route::post('sessions/{session_id}', 'SessionController@saveAll');

        Route::get('sessions/restart', 'SessionController@restart');
    });

});

Auth::routes(['register' => false]);

resources/views/includes/footer.blade.php
<footer class="bg-secondary py-2 py-lg-1">
	<div class="container">
		<div class="text-white mt-1">
			<i>"Vaarwel Walhalla, stralende wereld. Verga tot stof."</i>
		</div>
    	<nav class="pt-1 pb-1 navbar navbar-expand navbar-dark">

        	<div class="collapse navbar-collapse" id="mainNavbar">
        		<div class="navbar-nav">
                    <a class="nav-item nav-link" href="/">Home</a>
                    @if(false) {{-- Temporarily disabled until content is available. --}}
                        <a class="nav-item nav-link" href="/testimonials">Testimonials</a>
            		    <a class="nav-item nav-link" href="/photos">Foto's</a>
                    @endif
                    <a class="nav-item nav-link" href="/about">Over het Godenspel</a>
                    <a class="nav-item nav-link" href="/disclaimer">Disclaimer</a>
            		<a class="nav-item nav-link" href="/contact">Contact</a>
                </div>
            </div>
        </nav>
    </div>
</footer>

resources/views/includes/header.blade.php
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
    	<a class="navbar-brand" href="{{ route('admin.index') }}">ADMIN</a>
    	<button class="navbar-toggler" type="button" data-toggle="collapse" 
    		data-target="mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Menu openen">
    			<span class="navbar-toggler-icon"></span>	
    	</button>
    	
    	<div class="collapse navbar-collapse" id="mainNavbar">
    		<div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ route('admin.index') }}">Home</a>
                <a class="nav-item nav-link" href="{{ route('admin.testimonials.index') }}">Testimonials</a>
        		<a class="nav-item nav-link" href="{{ route('admin.photos.index') }}">Foto's</a>
        		<a class="nav-item nav-link" href="{{ route('admin.swaps.index') }}">Wissels</a>
            </div>
        </div>
    </nav>
</header>